//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int commentid { get; set; }
        public Nullable<int> movieid { get; set; }
        public Nullable<int> userid { get; set; }
        public string commentstatement { get; set; }
        public Nullable<System.DateTime> date { get; set; }
     //   public string date { get; set; }

        public virtual movies movies { get; set; }
        public virtual user user { get; set; }
    }
}
