//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class movieDatabaseEntities : DbContext
    {
        public movieDatabaseEntities()
            : base("name=movieDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actor> actor { get; set; }
        public virtual DbSet<actorInMovie> actorInMovie { get; set; }
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<movies> movies { get; set; }
        public virtual DbSet<rating> rating { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<watch_list> watch_list { get; set; }
    }
}
