//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movies()
        {
            this.actorInMovie = new HashSet<actorInMovie>();
            this.comment = new HashSet<comment>();
            this.genre = new HashSet<genre>();
            this.rating = new HashSet<rating>();
            this.watch_list = new HashSet<watch_list>();
        }
    
        public int movieid { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public string duration { get; set; }
        public string directorname { get; set; }
        public string overview { get; set; }
        public string pictureurl { get; set; }
        public string trailerurl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actorInMovie> actorInMovie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genre> genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating> rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<watch_list> watch_list { get; set; }
    }
}
